version: "3"
services:
  postgres:
    image: postgres:9.6.3
    ports:
      - 33333:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
  users:
    image: rsobnb/users
    ports:
      - 8080:8080
    environment:
      KUMULUZEE_DATASOURCES0_CONNECTIONURL: jdbc:postgresql://172.17.0.1:33333/users
    depends_on:
      - postgres