kumuluzee:
  name: real_estates
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/RealEstatesDS
      connection-url: jdbc:postgresql://172.17.0.1:33334/real_estates
      username: postgres
      password: postgres
      max-pool-size: 20