apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres-realestates-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-realestates
    spec:
      containers:
        - image: centos/postgresql-94-centos7
          name: postgres-realestates
          env:
            - name: POSTGRESQL_USER
              value: dbuser
            - name: POSTGRESQL_PASSWORD
              value: postgres
            - name: POSTGRESQL_DATABASE
              value: real_estates
          ports:
          - containerPort: 5433
            protocol: TCP