apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: realestates-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: realestates
    spec:
      containers:
      - image: ggrex/rsobnb-real_estates:0.3
        imagePullPolicy: Always
        name: realestates
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://real_estates:8081
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-realestates:5432/real_estates
          - name: KUMULUZEE_DATASOURCES0_USERNAME
            value: dbuser
          - name: KUMULUZEE_DATASOURCES0_PASSWORD
            value: postgres
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://168.1.149.41:32622/
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 3
        ports:
        - containerPort: 8081
          name: server
          protocol: TCP